# seaborn-style `sns.` aliases. Generated by data-raw (do not edit by hand).
# Collated last (zzz-*) so every aliased function is already defined.

#' seaborn-style `sns.` function aliases
#'
#' For copy-paste compatibility with Python, reaborn provides a `sns.`-prefixed
#' alias for every public plotting, palette, and theming function (R allows dots
#' in identifiers). So pasted seaborn code such as
#' `sns.scatterplot(data = df, x = "a", y = "b", hue = "g")` runs verbatim.
#' Each alias is identical to its unprefixed counterpart; see that function for
#' arguments and details.
#'
#' @return
#' Each `sns.`-prefixed object is the exact same function as its unprefixed
#' counterpart (`sns.scatterplot <- scatterplot`, and so on), so calling an
#' alias returns precisely what the counterpart returns. By category: the
#' plotting functions (e.g. `sns.scatterplot()`, `sns.histplot()`,
#' `sns.heatmap()`, `sns.pairplot()`, `sns.FacetGrid()`) return a `reaborn_plot`
#' object (a ggplot2/patchwork object that draws when printed), except
#' `sns.palplot()`, which draws a palette swatch and returns `NULL` invisibly;
#' the palette constructors (e.g. `sns.color_palette()`, `sns.husl_palette()`,
#' `sns.cubehelix_palette()`) return a character vector of hex colors, or a
#' `reaborn_cmap`; the color helpers `sns.desaturate()`, `sns.saturate()`, and
#' `sns.set_hls_values()` return a hex color string; `sns.axes_style()` and
#' `sns.plotting_context()` return a named list of style/context parameters;
#' `sns.despine()` and `sns.move_legend()` return a ggplot2 theme object to add
#' to a plot; `sns.load_dataset()` returns a data frame and
#' `sns.get_dataset_names()` a character vector; and the theming setters
#' (`sns.set_theme()`, `sns.set()`, `sns.set_style()`, `sns.set_context()`,
#' `sns.set_palette()`, `sns.set_color_codes()`, `sns.reset_defaults()`,
#' `sns.reset_orig()`) are called for their side effect of changing global plot
#' defaults and return their value invisibly. See each unprefixed function's own
#' help page for the precise structure and meaning of its return value.
#'
#' @name sns-aliases
#' @usage NULL
#' @aliases sns.scatterplot sns.lineplot sns.relplot sns.histplot sns.kdeplot sns.ecdfplot sns.rugplot sns.displot sns.boxplot sns.violinplot sns.boxenplot sns.stripplot sns.swarmplot sns.barplot sns.pointplot sns.countplot sns.catplot sns.regplot sns.residplot sns.lmplot sns.heatmap sns.clustermap sns.pairplot sns.jointplot sns.FacetGrid sns.palplot sns.dogplot sns.color_palette sns.hls_palette sns.husl_palette sns.mpl_palette sns.dark_palette sns.light_palette sns.diverging_palette sns.blend_palette sns.cubehelix_palette sns.set_color_codes sns.set_theme sns.set sns.reset_defaults sns.reset_orig sns.axes_style sns.set_style sns.plotting_context sns.set_context sns.set_palette sns.desaturate sns.saturate sns.set_hls_values sns.move_legend sns.despine sns.load_dataset sns.get_dataset_names
#' @export sns.scatterplot
#' @export sns.lineplot
#' @export sns.relplot
#' @export sns.histplot
#' @export sns.kdeplot
#' @export sns.ecdfplot
#' @export sns.rugplot
#' @export sns.displot
#' @export sns.boxplot
#' @export sns.violinplot
#' @export sns.boxenplot
#' @export sns.stripplot
#' @export sns.swarmplot
#' @export sns.barplot
#' @export sns.pointplot
#' @export sns.countplot
#' @export sns.catplot
#' @export sns.regplot
#' @export sns.residplot
#' @export sns.lmplot
#' @export sns.heatmap
#' @export sns.clustermap
#' @export sns.pairplot
#' @export sns.jointplot
#' @export sns.FacetGrid
#' @export sns.palplot
#' @export sns.dogplot
#' @export sns.color_palette
#' @export sns.hls_palette
#' @export sns.husl_palette
#' @export sns.mpl_palette
#' @export sns.dark_palette
#' @export sns.light_palette
#' @export sns.diverging_palette
#' @export sns.blend_palette
#' @export sns.cubehelix_palette
#' @export sns.set_color_codes
#' @export sns.set_theme
#' @export sns.set
#' @export sns.reset_defaults
#' @export sns.reset_orig
#' @export sns.axes_style
#' @export sns.set_style
#' @export sns.plotting_context
#' @export sns.set_context
#' @export sns.set_palette
#' @export sns.desaturate
#' @export sns.saturate
#' @export sns.set_hls_values
#' @export sns.move_legend
#' @export sns.despine
#' @export sns.load_dataset
#' @export sns.get_dataset_names
#' @examples
#' pen <- load_dataset("penguins")
#' p <- sns.scatterplot(data = pen, x = "bill_length_mm", y = "bill_depth_mm",
#'                      hue = "species")
NULL

sns.scatterplot <- scatterplot
sns.lineplot <- lineplot
sns.relplot <- relplot
sns.histplot <- histplot
sns.kdeplot <- kdeplot
sns.ecdfplot <- ecdfplot
sns.rugplot <- rugplot
sns.displot <- displot
sns.boxplot <- boxplot
sns.violinplot <- violinplot
sns.boxenplot <- boxenplot
sns.stripplot <- stripplot
sns.swarmplot <- swarmplot
sns.barplot <- barplot
sns.pointplot <- pointplot
sns.countplot <- countplot
sns.catplot <- catplot
sns.regplot <- regplot
sns.residplot <- residplot
sns.lmplot <- lmplot
sns.heatmap <- heatmap
sns.clustermap <- clustermap
sns.pairplot <- pairplot
sns.jointplot <- jointplot
sns.FacetGrid <- FacetGrid
sns.palplot <- palplot
sns.dogplot <- dogplot
sns.color_palette <- color_palette
sns.hls_palette <- hls_palette
sns.husl_palette <- husl_palette
sns.mpl_palette <- mpl_palette
sns.dark_palette <- dark_palette
sns.light_palette <- light_palette
sns.diverging_palette <- diverging_palette
sns.blend_palette <- blend_palette
sns.cubehelix_palette <- cubehelix_palette
sns.set_color_codes <- set_color_codes
sns.set_theme <- set_theme
sns.set <- set
sns.reset_defaults <- reset_defaults
sns.reset_orig <- reset_orig
sns.axes_style <- axes_style
sns.set_style <- set_style
sns.plotting_context <- plotting_context
sns.set_context <- set_context
sns.set_palette <- set_palette
sns.desaturate <- desaturate
sns.saturate <- saturate
sns.set_hls_values <- set_hls_values
sns.move_legend <- move_legend
sns.despine <- despine
sns.load_dataset <- load_dataset
sns.get_dataset_names <- get_dataset_names
