# Workflow derived from https://github.com/marketplace/actions/r-spellcheck-action

name: spellcheck

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master, release/**]

jobs:
  check:
    runs-on: ubuntu-latest
    name: Spellcheck
    container:
      image: rocker/tidyverse:4.1.2
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Spelling Check test
        uses: insightsengineering/r-spellcheck-action@v2
